<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DefineConstants>TASKS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../AAD.fs/YoLo.fs" />
    <Compile Include="../AAD.fs/Domain.fs" />
    <Compile Include="../AAD.fs/Awaitable.fs" />
    <Compile Include="../AAD.fs/ResourceOwner.fs" />
    <Compile Include="../AAD.fs/Requestor.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.84.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
  </ItemGroup>
</Project>