<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="YoLo.fs" />
    <Compile Include="Domain.fs" />
    <Compile Include="Awaitable.fs" />
    <Compile Include="Requestor.fs" />
    <Compile Include="ResourceOwner.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.84.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
  </ItemGroup>
</Project>