<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AAD.fs.tasks\AAD.fs.tasks.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ReadersAndWriters.fs" />
    <Compile Include="PartProtector.fs" />
    <Compile Include="Noop.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Giraffe" Version="6.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>
</Project>